FROM alpine:3.23

 RUN arch=$( ([ "$(arch)" = 'aarch64' ] && echo -n 'arm64') || ([ "$(arch)" = 'armv7l' ] && echo -n 'arm') || echo -n 'x86_64' ) \
  && apk update \
  && apk upgrade \
  && apk add \
    pdns \
    pdns-backend-sqlite3 \
    pdns-doc \
    sqlite \
  && wget -O subvars.tar.gz \
      https://github.com/TektonOps/subvars/releases/download/v0.1.5/subvars_Linux_${arch}.tar.gz \
  && tar -xzf subvars.tar.gz \
  && mv subvars /usr/local/bin/subvars \
  && chmod +x /usr/local/bin/subvars

RUN mkdir -p /run/pdns \
  && mkdir -p /var/lib/powerdns \
  && chown -R pdns: /etc/pdns /run/pdns /var/lib/powerdns

COPY pdns.conf.tpl docker-entrypoint.sh /

ENV VERSION=5.0 \
  PDNS_guardian=yes \
  PDNS_setuid=pdns \
  PDNS_setgid=pdns \
  PDNS_launch=gsqlite3

EXPOSE 53 53/udp

HEALTHCHECK --interval=10s --timeout=10s --retries=3 --start-period=2s CMD ["pdns_control", "ping"]

ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD [ "/usr/sbin/pdns_server" ]
